import CmpCard from "@/pageCom/Companies/CmpCard/cmpCard";
import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { Button } from "primereact/button";
import { useEffect } from "react";
import { useRecoilValueLoadable } from "recoil";
import { ROUTES } from "src/common/routes/main.routes";
import { CompanyDTO } from "src/models/compay.model";
import { CompanyService } from "src/services/company.service";
import { AtomCompanies } from "src/store/auth/company.store";

const CompaniesPage: NextPage = () => {
  const allCmps = useRecoilValueLoadable(AtomCompanies);
  const router = useRouter();

  console.log({ all: allCmps.contents });

  return (
    <div>
      <Head>
        <title>Jewells - Companies</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container p-3">
        <Button
          label="Create Company"
          icon="pi pi-plus"
          className="p-button-text"
          onClick={() => router.push(ROUTES.CREATE_COMPANIES)}
        />
        <div className=" row  mx-auto">
          {allCmps.state === "hasValue" &&
            allCmps.contents?.map((cmp: CompanyDTO) => {
              return <CmpCard cmp={cmp} key={cmp.company_id} />;
            })}
        </div>
      </div>
    </div>
  );
};

export default CompaniesPage;
